Repository quic/efficient-transformers, pull requests merged in 2024-10, with the labels that each got.

#139 Remove `index_url` dependency and extend python version compatibility
  README.md
  pyproject.toml
Labels: bugfix

#149 fix for token_type_ids
  QEfficient/generation/text_generation_inference.py
  QEfficient/utils/generate_inputs.py
Labels: in-review

#158 Consistency Check Failure is Fixed
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
Labels: in-review

#161 Example script and readme file for replicate_kv_head
  scripts/perplexity_computation/README.md
  scripts/perplexity_computation/__init__.py
  scripts/perplexity_computation/calculate_perplexity.py
  scripts/replicate_kv_head/README.md
  scripts/replicate_kv_head/__init__.py
  scripts/replicate_kv_head/replicate_kv_heads.py
Labels: enhancement

#98 Replacing assertions
  QEfficient/base/common.py
  QEfficient/compile/compile_helper.py
  QEfficient/exporter/export_hf_to_cloud_ai_100.py
  QEfficient/generation/cloud_infer.py
  QEfficient/generation/text_generation_inference.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/transform.py
  QEfficient/utils/_utils.py
Labels: good first issue, in-review

#123 Gemma, Gemma2 and CodeGemma support
  QEfficient/customop/__init__.py
  QEfficient/customop/rms_norm.py
  QEfficient/exporter/export_utils.py
  QEfficient/transformers/modeling_utils.py
  QEfficient/transformers/models/gemma/__init__.py
  QEfficient/transformers/models/gemma/modeling_gemma.py
  QEfficient/transformers/models/gemma2/__init__.py
  QEfficient/transformers/models/gemma2/modeling_gemma2.py
  QEfficient/transformers/pytorch_transforms.py
  QEfficient/utils/_utils.py
  README.md
  docs/source/validate.md
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/test_transformer_pytorch_transforms.py
Labels: model-enablement, in-review
