Repository quic/efficient-transformers, pull requests merged in 2024-12, with the labels that each got.

#193 Updated perplexity script
  scripts/perplexity_computation/calculate_perplexity.py
Labels: enhancement

#119 [eplatero] Add support for exporting and compiling models for SpD
  QEfficient/base/modeling_qeff.py
  QEfficient/generation/text_generation_inference.py
  QEfficient/peft/auto.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/models/pytorch_transforms.py
  QEfficient/transformers/spd/__init__.py
  QEfficient/transformers/spd/causal_lm_forward.py
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
  QEfficient/utils/run_utils.py
  docs/source/quick_start.md
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/test_transformer_pytorch_transforms.py
Labels: enhancement, in-review, vllm

#199 [QEff. Finetune] : Add Initial Phase-1 Support in QEff.
  QEfficient/cloud/finetune.py
  QEfficient/finetune/__init__.py
  QEfficient/finetune/configs/__init__.py
  QEfficient/finetune/configs/dataset_config.py
  QEfficient/finetune/configs/peft_config.py
  QEfficient/finetune/configs/training.py
  QEfficient/finetune/data/__init__.py
  QEfficient/finetune/dataset/__init__.py
  QEfficient/finetune/dataset/alpaca_dataset.py
  QEfficient/finetune/dataset/custom_dataset.py
  QEfficient/finetune/dataset/dataset_config.py
  QEfficient/finetune/dataset/grammar_dataset.py
  QEfficient/finetune/dataset/gsm8k_dataset.py
  QEfficient/finetune/dataset/samsum_dataset.py
  QEfficient/finetune/eval.py
  QEfficient/finetune/utils/__init__.py
  QEfficient/finetune/utils/config_utils.py
  QEfficient/finetune/utils/dataset_utils.py
  QEfficient/finetune/utils/plot_metrics.py
  QEfficient/finetune/utils/train_utils.py
  docs/index.md
  docs/source/finetune.md
  docs/source/quick_start.md
  pyproject.toml
  scripts/finetune/__init__.py
  scripts/finetune/run_ft_model.py
  tests/finetune/test_finetune.py
Labels: fine-tuning

#192 Support of AutoModel
  QEfficient/__init__.py
  QEfficient/base/__init__.py
  QEfficient/base/common.py
  QEfficient/base/modeling_qeff.py
  QEfficient/transformers/models/modeling_auto.py
  docs/source/hl_api.md
  scripts/Jenkinsfile
  tests/transformers/models/test_embedding_models.py
Labels: enhancement
