Repository quic/efficient-transformers, pull requests merged in 2024-09, with the labels that each got.

#105 Updated README.md with latest changes
  README.md
  docs/source/introduction.md
  docs/source/validate.md
Labels: documentation

#87 [Model Updates]: Update the rope calculations
  QEfficient/base/pytorch_transforms.py
  QEfficient/transformers/modeling_utils.py
  QEfficient/transformers/models/llama/modeling_llama.py
  QEfficient/transformers/models/mistral/modeling_mistral.py
  QEfficient/transformers/models/mixtral_moe/modeling_mixtral.py
  QEfficient/transformers/models/phi/modeling_phi.py
  QEfficient/transformers/models/phi3/modeling_phi3.py
  QEfficient/transformers/models/qwen2/modeling_qwen2.py
  QEfficient/transformers/models/starcoder2/modeling_starcoder2.py
  QEfficient/transformers/pytorch_transforms.py
  README.md
  pyproject.toml
  scripts/Jenkinsfile
  tests/transformers/test_transformer_pytorch_transforms.py
Labels: enhancement

#85 Peft Lora implementation
  QEfficient/__init__.py
  QEfficient/peft/__init__.py
  QEfficient/peft/auto.py
  QEfficient/peft/onnx_transforms.py
  QEfficient/peft/peft_model.py
  QEfficient/peft/pytorch_transforms.py
  QEfficient/utils/cache.py
  QEfficient/utils/constants.py
  docs/source/hl_api.md
  examples/peft_models.py
  tests/peft/test_peft_model.py
  tests/peft/test_peft_onnx_transforms.py
  tests/utils/test_cache.py
Labels: enhancement, peft

#112 Fixed Continuous Batching command
  docs/source/quick_start.md
Labels: documentation

#92 Add Support to compute Sample Perplexity
  scripts/README.md
  scripts/calculate_perplexity.py
Labels: enhancement

#118 add rope scaling to llama mainline and update readme
  QEfficient/transformers/models/llama/modeling_llama.py
  README.md
Labels: enhancement

#124 Update number of heads for MQA in Falcon
  QEfficient/utils/_utils.py
Labels: bugfix

#96 Add support for new model granite - Starcoder1 arch
  QEfficient/customop/__init__.py
  QEfficient/customop/ctx_scatter_gather.py
  QEfficient/customop/ctx_scatter_gather_cb.py
  QEfficient/exporter/export_utils.py
  QEfficient/transformers/cache_utils.py
  QEfficient/transformers/modeling_utils.py
  QEfficient/transformers/models/gpt_bigcode/__init__.py
  QEfficient/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
  QEfficient/transformers/pytorch_transforms.py
  QEfficient/utils/_utils.py
  README.md
  tests/transformers/models/test_causal_lm_models.py
Labels: enhancement, model-enablement
