Repository quic/efficient-transformers, pull requests merged in 2024-05, with the labels that each got.

#7 bugfix and checks for making sure tokenizer is always padded left
  QEfficient/cloud/execute.py
  QEfficient/cloud/export.py
  QEfficient/cloud/infer.py
  QEfficient/exporter/export_hf_to_cloud_ai_100.py
  QEfficient/exporter/export_utils.py
  QEfficient/generation/text_generation_inference.py
  QEfficient/utils/generate_inputs.py
  QEfficient/utils/run_utils.py
  README.md
  notebooks/QEfficientGPT2.ipynb
  notebooks/QEfficientMPT.ipynb
Labels: bug, good first issue

#3 renamed exec APIs
  QEfficient/cloud/execute.py
  QEfficient/cloud/infer.py
  QEfficient/generation/text_generation_inference.py
  README.md
  notebooks/QEfficientGPT2.ipynb
  notebooks/QEfficientMPT.ipynb
Labels: enhancement

#13 fix mdp config at compilation
  QEfficient/exporter/export_utils.py
Labels: bugfix

#11 Update infer and execute API to take prompts from txt file for BS>=1
  QEfficient/cloud/execute.py
  QEfficient/cloud/infer.py
  QEfficient/generation/text_generation_inference.py
  README.md
  examples/prompts.txt
  notebooks/QEfficientGPT2.ipynb
  notebooks/QEfficientMPT.ipynb
Labels: enhancement

#26 Add Json Based Pytest Pipeline for Scalability
  QEfficient/utils/constants.py
  scripts/specializations.json
  tests/CMakeLists.txt
  tests/config.json
  tests/transformer/models/codegen/test_modeling_codegen.py
  tests/transformer/models/gpt2/test_modeling_gpt2.py
  tests/transformer/models/llama/test_modeling_llama.py
  tests/transformer/models/mistral/test_modeling_mistral.py
  tests/transformer/models/mixtral_moe/test_modeling_mixtral.py
  tests/transformer/models/mpt/test_modeling_mpt.py
  tests/transformers/models/test_causal_lm_models.py
  tests/utils.py
Labels: enhancement
