Repository quic/efficient-transformers, pull requests merged in 2024-11, with the labels that each got.

#166 Fixed intermediate shape from projection
  QEfficient/transformers/models/gemma/modeling_gemma.py
Labels: in-review

#153 Finite lorax support
  QEfficient/generation/text_generation_inference.py
  QEfficient/peft/auto.py
  QEfficient/peft/lora/__init__.py
  QEfficient/peft/lora/auto.py
  QEfficient/peft/lora/layers.py
  QEfficient/peft/lora/lora_model.py
  QEfficient/peft/lora/pytorch_transforms.py
  QEfficient/transformers/models/llama/modeling_llama.py
  QEfficient/transformers/models/mistral/modeling_mistral.py
  docs/source/hl_api.md
  examples/lora_models.py
  tests/peft/lora/test_lora_model.py
Labels: in-review

#180 Docker-driven tests with latest SDKs
  scripts/Jenkinsfile
Labels: enhancement

#183 Enabled repeat KV heads for AWQ models
  QEfficient/transformers/quantizers/auto.py
  QEfficient/transformers/quantizers/quantizer_gptq.py
  QEfficient/utils/__init__.py
  scripts/replicate_kv_head/replicate_kv_heads.py
  tests/transformers/models/test_causal_lm_models.py
Labels: enhancement, quantization

#185 added full_batch_size to replicate_kv script
  QEfficient/cloud/infer.py
  scripts/replicate_kv_head/replicate_kv_heads.py
Labels: enhancement
