Repository quic/efficient-transformers, pull requests merged in 2025-03, with the labels that each got.

#203 Code for SDK configs Inclusion
  QEfficient/base/modeling_qeff.py
  QEfficient/peft/auto.py
  QEfficient/peft/lora/auto.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
  tests/peft/lora/test_lora_model.py
  tests/peft/test_peft_model.py
  tests/qnn_tests/test_causal_lm_models_qnn.py
  tests/text_generation/test_text_generation.py
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/models/test_embedding_models.py
  tests/transformers/models/test_prefix_caching.py
  tests/transformers/models/test_speech_seq2seq_models.py
  tests/transformers/spd/test_spd_inference.py
  tests/transformers/test_causal_lm.py
  tests/transformers/test_speech_seq2seq.py
Labels: in-review

#286 Minor Changes to AutoModelForSpeechSeq2Seq to better align with other models
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/models/whisper/modeling_whisper.py
  examples/speech_to_text/run_whisper_speech_to_text.py
  tests/transformers/models/test_speech_seq2seq_models.py
Labels: model-enablement

#313 BUGFIX: added patch for get_model_config to work properly for VLMs
  QEfficient/transformers/models/internvl/modeling_internvl.py
  QEfficient/transformers/models/llava/modeling_llava.py
Labels: bugfix
