Repository quic/efficient-transformers, pull requests merged in 2025-04, with the labels that each got.

#340 Enabled Models for TF-4.50.0
  QEfficient/transformers/models/gpt2/modeling_gpt2.py
  QEfficient/transformers/models/gptj/modeling_gptj.py
  QEfficient/transformers/models/granite/modeling_granite.py
  QEfficient/transformers/models/phi/modeling_phi.py
  QEfficient/transformers/models/phi3/modeling_phi3.py
  QEfficient/transformers/models/whisper/modeling_whisper.py
Labels: enhancement, 1.20.0

#331 Upgrading transformers version to latest 4.50
  QEfficient/transformers/cache_utils.py
  QEfficient/transformers/models/codegen/modeling_codegen.py
  QEfficient/transformers/models/falcon/modeling_falcon.py
  QEfficient/transformers/models/gemma/modeling_gemma.py
  QEfficient/transformers/models/gemma2/modeling_gemma2.py
  QEfficient/transformers/models/gpt2/modeling_gpt2.py
  QEfficient/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py
  QEfficient/transformers/models/gptj/modeling_gptj.py
  QEfficient/transformers/models/granite/modeling_granite.py
  QEfficient/transformers/models/llama/modeling_llama.py
  QEfficient/transformers/models/mistral/modeling_mistral.py
  QEfficient/transformers/models/mixtral_moe/modeling_mixtral.py
  QEfficient/transformers/models/mllama/modeling_mllama.py
  QEfficient/transformers/models/mpt/modeling_mpt.py
  QEfficient/transformers/models/phi/modeling_phi.py
  QEfficient/transformers/models/phi3/modeling_phi3.py
  QEfficient/transformers/models/pytorch_transforms.py
  QEfficient/transformers/models/qwen2/modeling_qwen2.py
  QEfficient/transformers/models/starcoder2/modeling_starcoder2.py
  QEfficient/transformers/models/whisper/modeling_whisper.py
  QEfficient/transformers/quantizers/quantizer_compressed_tensors.py
  pyproject.toml
Labels: 1.20.0, ready for review

#362 Granite MOE model
  QEfficient/transformers/models/granitemoe/__init__.py
  QEfficient/transformers/models/granitemoe/modeling_granitemoe.py
  QEfficient/transformers/models/pytorch_transforms.py
  README.md
  tests/transformers/models/test_causal_lm_models.py
Labels: 1.20.0, ready for review

#359 Onboarding Granite Vision
  QEfficient/transformers/models/llava_next/__init__.py
  QEfficient/transformers/models/llava_next/modeling_llava_next.py
  QEfficient/transformers/models/pytorch_transforms.py
  QEfficient/utils/constants.py
  docs/source/validate.md
  examples/granite_example/granite_vision_inference.py
  examples/granite_example/readme.md
Labels: enhancement, verified, 1.20.0

#317 Enabling VLLM test
  scripts/Jenkinsfile
  tests/vllm/test_qaic_output_consistency.py
Labels: 1.20.0, ready for review

#335 QNN Compilation path Support in QEFFBaseModel class.
  QEfficient/base/modeling_qeff.py
  QEfficient/compile/compile_helper.py
  QEfficient/compile/qnn_compiler.py
  QEfficient/peft/auto.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
  QEfficient/utils/generate_qnn_network_specialization_config.py
  docs/source/validate.md
  scripts/Jenkinsfile
  tests/qnn_tests/test_causal_lm_models_qnn.py
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/models/test_embedding_models.py
  tests/transformers/models/test_prefix_caching.py
  tests/transformers/models/test_speech_seq2seq_models.py
  tests/transformers/spd/test_pld_inference.py
  tests/transformers/spd/test_spd_inference.py
Labels: 1.20.0

#287 Enabled Infer CLI for VLM
  QEfficient/base/common.py
  QEfficient/cloud/infer.py
  QEfficient/transformers/modeling_utils.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  scripts/Jenkinsfile
  tests/cloud/test_infer_vlm.py
Labels: 1.20.0, ready for review

#374 QNN Compilation path Support in QEFFBaseModel class.
  QEfficient/base/modeling_qeff.py
  QEfficient/compile/compile_helper.py
  QEfficient/compile/qnn_compiler.py
  QEfficient/peft/auto.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
  QEfficient/utils/generate_qnn_network_specialization_config.py
  scripts/Jenkinsfile
  tests/qnn_tests/test_causal_lm_models_qnn.py
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/models/test_embedding_models.py
  tests/transformers/models/test_prefix_caching.py
  tests/transformers/models/test_speech_seq2seq_models.py
Labels: 1.20.0

#378 Enabling infer cli for VLMs
  QEfficient/base/common.py
  QEfficient/cloud/infer.py
  QEfficient/transformers/modeling_utils.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  scripts/Jenkinsfile
  tests/cloud/test_infer_vlm.py
Labels: 1.20.0

#336 Added changes to ensure mxint8 compilations of VLMs work.
  QEfficient/transformers/models/internvl/modeling_internvl.py
  QEfficient/transformers/models/llava/modeling_llava.py
  QEfficient/transformers/models/modeling_auto.py
Labels: 1.20.0

#375 Added customio for seq2seq models and updated input names
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/models/whisper/modeling_whisper.py
  tests/transformers/models/test_speech_seq2seq_models.py
Labels: 1.20.0

#337 VLM e2e test pipeline
  QEfficient/transformers/models/mllama/modeling_mllama.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  QEfficient/utils/generate_inputs.py
  QEfficient/utils/run_utils.py
  QEfficient/utils/test_utils.py
  scripts/Jenkinsfile
  tests/transformers/models/test_image_text_to_text_models.py
Labels: verified, 1.20.0
