Repository quic/efficient-transformers, pull requests merged in 2025-07, with the labels that each got.

#423 [Docs/Readme]: Main Readme updating for latest news and adding the onboarded features in docs
  README.md
  docs/source/introduction.md
  docs/source/quick_start.md
  docs/source/validate.md
Labels: 1.20.0

#479 MDP hash support
  QEfficient/base/modeling_qeff.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
Labels: 1.20.0

#492 MDP hash support
  QEfficient/base/modeling_qeff.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
  README.md
Labels: 1.20.0

#482 [QEff. Finetune]: Removed samsum dataset references from FT code.
  QEfficient/finetune/configs/dataset_config.py
  QEfficient/finetune/configs/training.py
  QEfficient/finetune/dataset/dataset_config.py
  QEfficient/finetune/dataset/samsum_dataset.py
  docs/source/finetune.md
Labels: fine-tuning, 1.21.0

#407 Dependency package upgrade
  pyproject.toml
  tests/peft/test_peft_onnx_transforms.py
Labels: 1.21.0
