Repository quic/efficient-transformers, pull requests merged in 2025-05, with the labels that each got.

#306 SpD, multiprojection heads
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/models/pytorch_transforms.py
  QEfficient/transformers/post_processing.py
  QEfficient/transformers/spd/spd_transform_forward.py
  QEfficient/transformers/spd/turbo.py
  QEfficient/utils/_utils.py
  QEfficient/utils/checkpoint_utils.py
  QEfficient/utils/spd_utils.py
  docs/source/quick_start.md
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/spd/test_pld_inference.py
  tests/transformers/spd/test_spd_inference.py
  tests/transformers/test_transformer_pytorch_transforms.py
Labels: enhancement, 1.20.0

#379 [Bug Fix]: qpc sdk config dump issue fixing
  QEfficient/utils/_utils.py
  QEfficient/utils/constants.py
Labels: 1.20.0

#393 Adding compilation support for io_encrypt flag
  QEfficient/cloud/compile.py
  QEfficient/cloud/infer.py
  QEfficient/compile/compile_helper.py
  QEfficient/transformers/models/modeling_auto.py
Labels: 1.20.0

#289 [QEff Finetune]: Refactor the finetune main __call__
  QEfficient/cloud/finetune.py
  QEfficient/finetune/configs/peft_config.py
  QEfficient/finetune/configs/training.py
  QEfficient/finetune/eval.py
  QEfficient/finetune/utils/config_utils.py
  QEfficient/finetune/utils/train_utils.py
  scripts/Jenkinsfile
  scripts/finetune/run_ft_model.py
  tests/finetune/test_finetune.py
Labels: enhancement, fine-tuning

#384 Hash bug fix pr
  QEfficient/transformers/models/modeling_auto.py
  tests/transformers/models/test_causal_lm_models.py
  tests/transformers/models/test_embedding_models.py
  tests/transformers/models/test_speech_seq2seq_models.py
Labels: bugfix

#419 Fix for replicate kv heads for release 1.20.0 branch
  scripts/replicate_kv_head/README.md
  scripts/replicate_kv_head/replicate_kv_heads.py
Labels: bug, bugfix, 1.20.0
