Repository quic/efficient-transformers, pull requests merged in 2025-06, with the labels that each got.

#424 Features upgrade of `Embedding model`
  QEfficient/__init__.py
  QEfficient/transformers/embeddings/__init__.py
  QEfficient/transformers/embeddings/embedding_utils.py
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/models/pytorch_transforms.py
  QEfficient/utils/__init__.py
  QEfficient/utils/_utils.py
  examples/embedding_model.py
  tests/transformers/models/test_embedding_models.py
Labels: 1.20.0, ready for review

#444 Bug fix for mllama
  QEfficient/transformers/models/modeling_auto.py
Labels: bugfix

#437 BUGFIX: Enabled separate folder creation for different num_devices
  QEfficient/base/modeling_qeff.py
Labels: 1.20.0

#476 Gemma 3 minor fixes
  QEfficient/transformers/cache_utils.py
  QEfficient/transformers/models/gemma3/modeling_gemma3.py
  README.md
  docs/source/validate.md
  examples/gemma3_example/fp32_mm.yaml
  examples/gemma3_example/gemma3_mm.py
  tests/transformers/models/test_image_text_to_text_models.py
Labels: 1.20.0

#467 Bug fix for spdTransform
  QEfficient/transformers/models/modeling_auto.py
  QEfficient/transformers/models/pytorch_transforms.py
Labels: 1.20.0
